Reg
idfedorov09/SofFYS pull request #21
Opened 2023-09-26 19:33 UTC by ThePrax12

Сделал файлик с регистрацией(RegFetcher) в UserResponse добавил новое поле message(сообщение от пользователя), разбил состояние бота (Registration на Cap_Registration и Team_Registration), поменял чуть чуть GeneralFetcher. ПОЙДУ ЗА ПИВОМ

2023-09-26 20:21 UTC, idfedorov09 requested changes
занеси в expContainer новое поле (типа registrationStage), которое содержит инфу о том на каком этапе регистрации мы сейчас (это тоже enum,  создай его плиз)

2023-09-26 20:21 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/enums/BotStage.kt
> +    TEAM_REGISTRATION,
дай плиз названия получше типа CAPTAIN_REGISTRATION и TEAMS_AUTH

2023-09-26 20:21 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/data/model/UserResponse.kt
> +    val message: String? = null, // Сообщение от пользователя(в частности при регистрации), возможно надо изменить, я добавил, чтобы код был рабочим
messageText

2023-09-26 20:32 UTC, ThePrax12 commented on src/main/java/ru/idfedorov09/telegram/bot/data/model/UserResponse.kt
> +    val message: String? = null, // Сообщение от пользователя(в частности при регистрации), возможно надо изменить, я добавил, чтобы код был рабочим
ИСПРАВИЛЛЛ

2023-09-26 20:35 UTC, idfedorov09 requested changes

2023-09-26 20:35 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/FlowConfiguration.kt
>                      group(condition = { exp.botStage == BotStage.REGISTRATION }) {
пропиши фетчер сюда пж

2023-09-26 20:37 UTC, ThePrax12 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/FlowConfiguration.kt
>                      group(condition = { exp.botStage == BotStage.REGISTRATION }) {
SDELAL

2023-09-26 20:39 UTC, idfedorov09 requested changes

2023-09-26 20:39 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +
сложно читается, скинь пж это все в отдельные функции

2023-09-27 00:06 UTC, idfedorov09 requested changes

2023-09-27 00:06 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +                        messageFromCap(tui, userResponse, bot)
я бы сделал название методов более говорящими: selectTeamName() и confirmTeamCreate() например

2023-09-27 00:06 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +                        buttonFromCap(tui, update)
confirmTeamCreate()

2023-09-27 00:06 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +                        buttonFromCap(tui, update)
ну или типа того

2023-09-27 00:06 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +        val teamName = userResponse.messageText?.replace(" ", "") ?: return
ты вообще все пробелы решил убрать? Я только про те что вначале и в конце говорил

2023-09-27 00:06 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +        val teamName = userResponse.messageText?.replace(" ", "") ?: return
а как же название "ифтис сила"

2023-09-27 00:06 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +                "Вы точно хотите заоегестрировать команду **$teamName**?",
очепятка но не критично

2023-09-27 00:06 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +        if (answer.substring(0, 12) == "team_confirm") {
проще и читабельнее проверять через startsWith, погугли

2023-09-27 00:06 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/fetcher/RegFetcher.kt
> +                teamId = answer.toLong(),
answer всегда сможет в лонг спарситься? вроде безопаснее через toLongOrNull

2023-09-27 16:51 UTC, ThePrax12 commented
Сделал файлик с регистрацией пользователя(UserRegFetcher) (отправляет сообщения всем пользователям не капитанам), поменял чуть чуть GeneralFetcher, исправил ошибки, описанные тобой выше.

2023-09-27 20:41 UTC, idfedorov09 approved these changes

2023-09-27 20:41 UTC, merged

2023-10-01 20:14 UTC, idfedorov09 commented on src/main/java/ru/idfedorov09/telegram/bot/flow/FlowConfiguration.kt
>                      group(condition = { exp.botStage == BotStage.REGISTRATION }) {
> SDELAL

Zделал